#ifndef PROJECT_INCLUDE_STATE_T_H_
#define PROJECT_INCLUDE_STATE_T_H_

typedef enum {
    STATE_USER_NAME,
    STATE_MAIL_NAME,
    STATE_DOMAIN,
    STATE_END,
    STATE_ERROR
} state_t;

#endif  // PROJECT_INCLUDE_STATE_T_H_
