dist:     focal    
sudo:     required  

language: cpp      

os:
    - linux

compiler:
    - gcc

before_install:
    - sudo apt-get install libgtest-dev
    - sudo apt-get install valgrind
    - pip3 install cpplint
    - sudo apt-get install cppcheck
    - pip3 install gcovr
    - sudo apt install gcovr
script:
    - ./linters/run.sh --local
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd tests && ./tests
    - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no --error-exitcode=1 ./tests
    - cd ../../ && gcovr -r .

