
name: Tests

on: [push]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install libs
        run: |
          sudo apt install cmake
          sudo apt-get install libgtest-dev
          sudo apt-get install valgrind
          sudo apt-get install cppcheck
          # pip3 install cpplint

      - name: build
        run: |
          #cppcheck --version
          ls -lah
          pwd
          mkdir build
          cd build
          cmake ..
          make
          cd tests && ./tests
          valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no --error-exitcode=1 ./tests
